import subprocess
import os

env = Environment() 

#path variables
doms_directory = 'third_party/ascend_doms/'
messaging_directory = doms_directory+'messaging/'
messaging_lib = messaging_directory+'libs/'
messaging_def = messaging_directory+'definitions/'

#create proto files
if(os.path.isdir(messaging_directory)):
    subprocess.check_call(["mkdir","-p", messaging_directory+"libs"])
    subprocess.check_call("protoc -I=" + messaging_def + " --cpp_out=" + messaging_lib + " " + messaging_def+'msgDef.proto', shell=True)
else:
    print("SUBMODULES NEED TO BE PULLED, EXECUTE IN TOP DIRECTORY: \"git submodule update --init --recursive\"")
    exit(1)

#messaging
messaging_files = Glob(messaging_lib + '*.cc')
messaging_files.extend(['drone_msg.cpp'])

#drone files
drone_files = ['drone.cpp','video_transmission.cpp',messaging_files]

#opencv
opencv = ['opencv_core','opencv_highgui','opencv_imgcodecs']

#DOMS fields
doms_files = Glob(doms_directory + "*.cpp")

#DJI OSDK
osdk_lib='third_party/Onboard-SDK-3.6.1/build/libs'

env=Environment(
    CPPDEFINES=[],
    CCFLAGS=['-g'],
    LIBS=['zmq', 'pqxx' ,'pq','protobuf',opencv,'raspicam','raspicam_cv','djiosdk-core'],
	LIBPATH=['/opt/vc/lib/','/usr/local/lib/',messaging_lib,osdk_lib],
    CPPPATH=['third_party/cpp-base64','/usr/local/include',messaging_lib,doms_directory],
    SCONS_CXX_STANDARD='c++14')

env.Program('drone', ['drone_main.cpp',drone_files, doms_files ])
