import subprocess
import os

env = Environment() 

#path variables
doms_directory = 'third_party/ascend_doms/'
messaging_directory = doms_directory+'messaging/'
messaging_lib = messaging_directory+'libs/'
messaging_def = messaging_directory+'definitions/'

#create proto files
if(os.path.isdir(messaging_directory)):
    subprocess.check_call(["mkdir","-p", messaging_directory+"libs"])
    subprocess.check_call("protoc -I=" + messaging_def + " --cpp_out=" + messaging_lib + " " + messaging_def+'msgDef.proto', shell=True)
else:
    print("SUBMODULES NEED TO BE PULLED, EXECUTE IN TOP DIRECTORY: \"git submodule update --init --recursive\"")
    exit(1)

#drone files
drone_files = ['drone.cpp',
    'manual_control.cpp',
    'waypoints.cpp',
    'drone_msg.cpp',
    'px4_sensors.cpp',
    'external_sensors.cpp',
    'package_control.cpp'
    ]

#shared fields
doms_files = Glob(doms_directory + "*.cpp")
messaging_files = Glob(messaging_lib + '*.cc')

env=Environment(
    CPPDEFINES=[],
    CCFLAGS=['-g'],
    LIBS=['zmq','protobuf','curses','mavsdk',
        'mavsdk_shell','mavsdk_action',
        'mavsdk_telemetry','mavsdk_offboard',
        'mavsdk_mission','mavsdk_calibration', 'mavsdk_manual_control',
        'pthread','libboost_system','wiringPi', 'libcurl'],
	LIBPATH=['/opt/vc/lib/','/usr/local/lib/',messaging_lib],
    CPPPATH=['include/','third_party/cpp-base64','/usr/local/include',
        '/usr/local/include/mavsdk',messaging_lib,doms_directory],
    SCONS_CXX_STANDARD='c++14')

#store *.o elsewhere
env.VariantDir('bin', 'src', duplicate=0)
drone_files = ['bin/'+path for path in drone_files]

#compile
env.Program('drone', ['bin/drone_main.cpp',drone_files, doms_files, messaging_files])

#compile kill program
env.Program('kill_drone', ['bin/kill_drone.cpp',drone_files, doms_files, messaging_files])
