# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msgDef.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='msgDef.proto',
  package='ascend',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\x0cmsgDef.proto\x12\x06\x61scend\"N\n\rheartbeat_msg\x12\x0b\n\x03lat\x18\x01 \x02(\x01\x12\x0b\n\x03lng\x18\x02 \x02(\x01\x12\x0b\n\x03\x61lt\x18\x03 \x02(\x01\x12\x16\n\x0e\x62\x61t_percentage\x18\x04 \x02(\x05\"I\n\x0bmove_offset\x12\t\n\x01x\x18\x01 \x02(\x02\x12\t\n\x01y\x18\x02 \x02(\x02\x12\t\n\x01z\x18\x03 \x02(\x02\x12\x0c\n\x04rate\x18\x04 \x02(\x02\x12\x0b\n\x03yaw\x18\x05 \x01(\x02\" \n\x10stop_remote_conn\x12\x0c\n\x04succ\x18\x01 \x02(\x08\"6\n\x0e\x61\x63tion_cmd_msg\x12$\n\x03\x63md\x18\x01 \x02(\x0e\x32\x17.ascend.action_cmd_enum\"!\n\x11initiate_land_msg\x12\x0c\n\x04land\x18\x01 \x02(\x08\"\x81\x02\n\x03msg\x12\x0c\n\x04name\x18\x01 \x02(\t\x12*\n\theartbeat\x18\x02 \x01(\x0b\x32\x15.ascend.heartbeat_msgH\x00\x12%\n\x06offset\x18\x06 \x01(\x0b\x32\x13.ascend.move_offsetH\x00\x12/\n\x0bstop_remote\x18\x0b \x01(\x0b\x32\x18.ascend.stop_remote_connH\x00\x12,\n\naction_cmd\x18\x0c \x01(\x0b\x32\x16.ascend.action_cmd_msgH\x00\x12\x32\n\rinitiate_land\x18\r \x01(\x0b\x32\x19.ascend.initiate_land_msgH\x00\x42\x06\n\x04type*d\n\x0f\x61\x63tion_cmd_enum\x12\x0b\n\x07TAKEOFF\x10\x00\x12\x08\n\x04LAND\x10\x01\x12\x0e\n\nAPRIL_LAND\x10\x02\x12\n\n\x06PICKUP\x10\x03\x12\x0b\n\x07\x44ROPOFF\x10\x04\x12\x08\n\x04KILL\x10\x05\x12\x07\n\x03\x41RM\x10\x06'
)

_ACTION_CMD_ENUM = _descriptor.EnumDescriptor(
  name='action_cmd_enum',
  full_name='ascend.action_cmd_enum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TAKEOFF', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LAND', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='APRIL_LAND', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PICKUP', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DROPOFF', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='KILL', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ARM', index=6, number=6,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=564,
  serialized_end=664,
)
_sym_db.RegisterEnumDescriptor(_ACTION_CMD_ENUM)

action_cmd_enum = enum_type_wrapper.EnumTypeWrapper(_ACTION_CMD_ENUM)
TAKEOFF = 0
LAND = 1
APRIL_LAND = 2
PICKUP = 3
DROPOFF = 4
KILL = 5
ARM = 6



_HEARTBEAT_MSG = _descriptor.Descriptor(
  name='heartbeat_msg',
  full_name='ascend.heartbeat_msg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lat', full_name='ascend.heartbeat_msg.lat', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lng', full_name='ascend.heartbeat_msg.lng', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='alt', full_name='ascend.heartbeat_msg.alt', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bat_percentage', full_name='ascend.heartbeat_msg.bat_percentage', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=102,
)


_MOVE_OFFSET = _descriptor.Descriptor(
  name='move_offset',
  full_name='ascend.move_offset',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='ascend.move_offset.x', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='ascend.move_offset.y', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='ascend.move_offset.z', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rate', full_name='ascend.move_offset.rate', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='yaw', full_name='ascend.move_offset.yaw', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=177,
)


_STOP_REMOTE_CONN = _descriptor.Descriptor(
  name='stop_remote_conn',
  full_name='ascend.stop_remote_conn',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='succ', full_name='ascend.stop_remote_conn.succ', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=179,
  serialized_end=211,
)


_ACTION_CMD_MSG = _descriptor.Descriptor(
  name='action_cmd_msg',
  full_name='ascend.action_cmd_msg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cmd', full_name='ascend.action_cmd_msg.cmd', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=213,
  serialized_end=267,
)


_INITIATE_LAND_MSG = _descriptor.Descriptor(
  name='initiate_land_msg',
  full_name='ascend.initiate_land_msg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='land', full_name='ascend.initiate_land_msg.land', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=269,
  serialized_end=302,
)


_MSG = _descriptor.Descriptor(
  name='msg',
  full_name='ascend.msg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ascend.msg.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='heartbeat', full_name='ascend.msg.heartbeat', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='offset', full_name='ascend.msg.offset', index=2,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stop_remote', full_name='ascend.msg.stop_remote', index=3,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='action_cmd', full_name='ascend.msg.action_cmd', index=4,
      number=12, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='initiate_land', full_name='ascend.msg.initiate_land', index=5,
      number=13, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='type', full_name='ascend.msg.type',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=305,
  serialized_end=562,
)

_ACTION_CMD_MSG.fields_by_name['cmd'].enum_type = _ACTION_CMD_ENUM
_MSG.fields_by_name['heartbeat'].message_type = _HEARTBEAT_MSG
_MSG.fields_by_name['offset'].message_type = _MOVE_OFFSET
_MSG.fields_by_name['stop_remote'].message_type = _STOP_REMOTE_CONN
_MSG.fields_by_name['action_cmd'].message_type = _ACTION_CMD_MSG
_MSG.fields_by_name['initiate_land'].message_type = _INITIATE_LAND_MSG
_MSG.oneofs_by_name['type'].fields.append(
  _MSG.fields_by_name['heartbeat'])
_MSG.fields_by_name['heartbeat'].containing_oneof = _MSG.oneofs_by_name['type']
_MSG.oneofs_by_name['type'].fields.append(
  _MSG.fields_by_name['offset'])
_MSG.fields_by_name['offset'].containing_oneof = _MSG.oneofs_by_name['type']
_MSG.oneofs_by_name['type'].fields.append(
  _MSG.fields_by_name['stop_remote'])
_MSG.fields_by_name['stop_remote'].containing_oneof = _MSG.oneofs_by_name['type']
_MSG.oneofs_by_name['type'].fields.append(
  _MSG.fields_by_name['action_cmd'])
_MSG.fields_by_name['action_cmd'].containing_oneof = _MSG.oneofs_by_name['type']
_MSG.oneofs_by_name['type'].fields.append(
  _MSG.fields_by_name['initiate_land'])
_MSG.fields_by_name['initiate_land'].containing_oneof = _MSG.oneofs_by_name['type']
DESCRIPTOR.message_types_by_name['heartbeat_msg'] = _HEARTBEAT_MSG
DESCRIPTOR.message_types_by_name['move_offset'] = _MOVE_OFFSET
DESCRIPTOR.message_types_by_name['stop_remote_conn'] = _STOP_REMOTE_CONN
DESCRIPTOR.message_types_by_name['action_cmd_msg'] = _ACTION_CMD_MSG
DESCRIPTOR.message_types_by_name['initiate_land_msg'] = _INITIATE_LAND_MSG
DESCRIPTOR.message_types_by_name['msg'] = _MSG
DESCRIPTOR.enum_types_by_name['action_cmd_enum'] = _ACTION_CMD_ENUM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

heartbeat_msg = _reflection.GeneratedProtocolMessageType('heartbeat_msg', (_message.Message,), {
  'DESCRIPTOR' : _HEARTBEAT_MSG,
  '__module__' : 'msgDef_pb2'
  # @@protoc_insertion_point(class_scope:ascend.heartbeat_msg)
  })
_sym_db.RegisterMessage(heartbeat_msg)

move_offset = _reflection.GeneratedProtocolMessageType('move_offset', (_message.Message,), {
  'DESCRIPTOR' : _MOVE_OFFSET,
  '__module__' : 'msgDef_pb2'
  # @@protoc_insertion_point(class_scope:ascend.move_offset)
  })
_sym_db.RegisterMessage(move_offset)

stop_remote_conn = _reflection.GeneratedProtocolMessageType('stop_remote_conn', (_message.Message,), {
  'DESCRIPTOR' : _STOP_REMOTE_CONN,
  '__module__' : 'msgDef_pb2'
  # @@protoc_insertion_point(class_scope:ascend.stop_remote_conn)
  })
_sym_db.RegisterMessage(stop_remote_conn)

action_cmd_msg = _reflection.GeneratedProtocolMessageType('action_cmd_msg', (_message.Message,), {
  'DESCRIPTOR' : _ACTION_CMD_MSG,
  '__module__' : 'msgDef_pb2'
  # @@protoc_insertion_point(class_scope:ascend.action_cmd_msg)
  })
_sym_db.RegisterMessage(action_cmd_msg)

initiate_land_msg = _reflection.GeneratedProtocolMessageType('initiate_land_msg', (_message.Message,), {
  'DESCRIPTOR' : _INITIATE_LAND_MSG,
  '__module__' : 'msgDef_pb2'
  # @@protoc_insertion_point(class_scope:ascend.initiate_land_msg)
  })
_sym_db.RegisterMessage(initiate_land_msg)

msg = _reflection.GeneratedProtocolMessageType('msg', (_message.Message,), {
  'DESCRIPTOR' : _MSG,
  '__module__' : 'msgDef_pb2'
  # @@protoc_insertion_point(class_scope:ascend.msg)
  })
_sym_db.RegisterMessage(msg)


# @@protoc_insertion_point(module_scope)
